- name: Generate index.json
  run: |
    python - <<'PY'
    import json, os, time
    from urllib.parse import quote

    imgs = []
    for root, _, files in os.walk("images"):
        for f in files:
            if f.lower().endswith((".jpg",".jpeg",".png",".gif",".webp")):
                p = os.path.join(root, f).replace("\\","/")
                imgs.append(p)

    # RAW GitHub URLs only (no jsDelivr)
    base = "https://raw.githubusercontent.com/walking-casino/autobot-images/main"
    urls = [f"{base}/{quote(p, safe='/@')}" for p in imgs]

    out = {
      "version": 1,
      "updated": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
      "images": sorted(urls)
    }

    with open("index.json","w") as fp:
      json.dump(out, fp, indent=2)

    print("Wrote index.json with", len(urls), "images (RAW)")
    PY
